### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by jzohrab**

### CODE REVIEW

**Comment by jzohrab** [comment]
Fixing lint errors that showed up in PR #138 .

**Comment by jzohrab** [comment]
Fixing Lint errors as they show up.  Currently adding docstrings for macros.

**Comment by jzohrab** [comment]
Sorry I'm polluting this PR with all sorts of failed test runs, I can't lint locally so I'm abusing CI.

**Comment by alphapapa** [comment]
You can lint locally!  Use https://github.com/alphapapa/makem.sh.  That's what I made it for, it works on both CI and locally.  :)

**Comment by alphapapa** [comment]
BTW, please don't wrap lines that linting complains are too long.  In some cases I prefer them, because they better preserve the shape of the code.

**Comment by jzohrab** [comment]
Thanks for the note about makem.sh, I'll check that out if things keep failing.  Ack on not wrapping long lines, so far I've only wrapped one docstring that you wrote.

**Comment by jzohrab** [comment]
Hi @alphapapa , the Lint tests now pass.  I haven't fixed the failing tests.

If you'd like, I can squash all of this down to a single commit to keep the history cleaner, or squash them in categories (e.g., adding docstrings, fixing varnames, shorting lines, updating method).  The changes are all for Lint only.  Let me know, thanks! z

**Comment by alphapapa** [comment]
Before going any further, please unwrap the lines you wrapped.  Remember that they will be displayed to the user as you have wrapped them, and since they start at the column they do in the source code, the lines in the resulting docstring will be very short.  That's why they should not be wrapped in the source code.

**Comment by jzohrab** [comment]
Sure thing re unwrapping the wrapped lines.  I don't know Lisp at all and so I wasn't aware of the issues with wrapping!  If the Linting fails after unwrapping I won't know how to handle that, so we'll see how it goes.

**Comment by alphapapa** [comment]
In some cases lint warnings simply have to be ignored.  Linters are tools, not masters.  ;)

**Comment by jzohrab** [comment]
Unfortunately I don't know how to fix those warnings so that CI passes, so here the tool _is_ the master.  Or I'm a tool.  Who knows. :-)   Fix is coming in one minute.

**Comment by jzohrab** [comment]
With the unwrapped lines Linting fails.  I can't see how to disable the long line check in CI, and googling for a long time gives no hints.  Any thoughts?

fyi, currently the failing line is:

```
The docstring will be, \"Divide ALL-ITEMS into groups based on DOCSTRING-ENDING.\".
```

If you're fine with the Lint failures, let me know if/how you'd like this branch cleaned up.  Thanks!

**Comment by alphapapa** [comment]
As I said, some lint warnings simply have to be ignored.

Here are my requests before merging this:

1.  Please remove hunks that make wrapping-related changes.  In this PR, at least, I'd prefer not to make any wrapping-related changes, and in general I prefer that PRs touch the minimal number of lines, and only ones related to their purpose.
2.  The added docstrings are appreciated.  Please remove the blank lines in them, however.  For simple docstrings like that, blank lines between sentences aren't necessary and increase the visual size of the code.  Generally, blank lines like that are only used for long, complicated docstrings with many arguments and explanations.
3.  This change seems unnecessary and makes the explanation less clear:
```diff
- The function will be named `org-super-agenda--auto-group-NAME'.
+ For the function name, NAME is concatenated to `org-super-agenda--auto-group-'.
```
If that change was made to placate `checkdoc`, I'd prefer not to make it at this time.

4.  If you need help running lints and tests locally with `makem.sh` (which is the script that runs in CI also), please ask.  Please don't use the force-push-to-PR-to-cause-CI-to-run method anymore.  It's deluging my inbox with emails.  If you must use the CI for that, please do it in a non-PR branch on your fork so it won't email me.

Thanks.

**Comment by jzohrab** [comment]
Got it.  Responses:

1. Will do.
2. Thanks, I followed existing code examples, but will remove them.
3. Yes, that was why I made that change.  I'll undo it, apologies.
4. CI isn't running on my branches on my fork.  I'll try PRs there to see if the github hooks pick it up.  I wasn't aware you were getting flooded with emails, sorry about that!

I was hoping that this would be a quick change, it's just lint errors, and didn't think this would become such a time sink for you or me.  :-(  Alas.  Thanks, I'll see what I can do locally with tests running and then will squash this to the minimum set of changes.

**Comment by jzohrab** [comment]
Closing this PR while I continue working on the branch.

**Pull request closed without merging**
