### PR TITLE
Fix #17: Use (org-get-tags-at) instead of headline regex.

### LINKED ISSUE #17: Selector ":tag" do not working with org-agenda-show-inherited-tags equal to nil
For example if we have such file:

\* TODO Parent                                       :tag:
** TODO Children

And if we call then such code:

`
   (let ((org-agenda-show-inherited-tags nil)
          (org-super-agenda-groups '((:name "With tag"
                                          :tag "tag"))))
    (org-agenda nil "t"))
`

We will see:

With tag
TODO Parent

Other items
TODO Children

### PR DESCRIPTION
**Pull request by mskorzhinskiy**
This commit also adds a customization point for this behaviour. The
default behaviour left untouched.

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks for submitting this, but I don't think it's necessary.  If `org-agenda-use-tag-inheritance` is non-nil, each item should already have its inherited tags.  For example, here's a test that you can put in `test/test.el` and run with `org-super-agenda--test-show-this-test`, and you'll see that items that inherit the `universe` tag show up in the list with that tag, such as the `Take over the world` item:
```el
(ert-deftest org-super-agenda--test-:tag-with-inheritance ()
  (should (org-super-agenda--test-run
           :let* ((org-agenda-use-tag-inheritance t))
           :groups '((:tag "universe")))))
```
Please let me know if it doesn't work for you, because that should be a bug.

Thanks.

**Comment by mskorzhinskiy** [comment]
Do I understand it correctly that the idea behind this that I should use 'org-agenda-use-tag-inheritance' to whole agenda buffer?

I.e. if I enable this, it would mean that my agenda items will have all the inherited tags, but in my setup it could be a pretty long list. So it the reason why I want this patch, is to not be distracted by pretty noisy and long list of inherited tags.

In short, I want the behaviour like the 'org-agenda-use-tag-inheritance' is applied only inside the group filtering, but not globally.

Or I didn't catch you here?

**Comment by alphapapa** [comment]
Ah, I understand.  Well, this is not a good way to accomplish that, because it will be very inefficient and slow.  If you look at the code for `org-get-tags-at`, you can see that it scans every parent heading for every heading, collecting a list of tags repeatedly, even if it discards them at the end.  The Org agenda has already done this work by the time we run this package, and has collected all the tags in the text property.

A better option might be to just get the non-inherited tags for each heading, and replace them after the agenda has been created and grouped.  You could write this as a post-processing function, the same way this package works.  Then you could add it as the final step in your Emacs config, independent of this package.

**Comment by alphapapa** [comment]
I'm going to close this now, but feel free to continue the discussion if you like.

**Pull request closed without merging**
