### PR TITLE
Fix: Require seq package

### PR DESCRIPTION
**Pull request by cryptorick**
### Issue

For minimal Emacs configurations, enabling `org-super-agenda` and
then generating an agenda will produce the following runtime error.
```
org-super-agenda--group-tag: Symbol’s function definition is void: seq-intersection
```

### Solution

Very simple: just `require` the `seq` package/library, as the code
still calls `seq-intersection` and `seq-difference` (at least).

### CODE REVIEW

**Comment by cryptorick** [comment]
Thanks for this package.  Great code!

**Comment by alphapapa** [comment]
Thanks, I'll merge this soon.  Nice avatar, BTW.  ;)

**Comment by alphapapa** [comment]
Ah, sorry, I keep forgetting to go through these PRs...

**Comment by cryptorick** [comment]
heh, np. we're very much alike! ha! cheers!

**Comment by alphapapa** [comment]
Thanks for your contribution, and your patience!

**Pull request merged**
