### PR TITLE
Add the :take selector to limit number of entries in a group

### PR DESCRIPTION
**Pull request by pkazmier**
Here is the PR for #172. I changed the name of the selector from `:head` to `:take`. In addition, I updated `README.org` to document the new selector. As a very infrequent visitor to Elisp-land, I was unable to understand your test framework and could not figure out how to add a test case.

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks, this looks great.  I'll take care of adding a test.  I haven't really documented the bespoke test system, so I don't expect anyone else to understand how it works, haha.

FYI, there are some other PRs that have been waiting, so to be fair to their contributors, I should probably take care of theirs first.  So it might be a little while before I get to merging this.  :)

**Comment by pkazmier** [comment]
I've noticed a flurry of activity lately in org-ql, any chance this could make it to your radar if you turn your attention to org-super-agenda? Thanks!

**Comment by alphapapa** [comment]
Yes, I'm going through 1.3-targeted issues now.  :)

**Comment by alphapapa** [comment]
@pkazmier Nitpick: Would you mind ensuring that there are two spaces between sentences in the docstrings and readme?  Thanks.

**Comment by pkazmier** [comment]
No problem and done.

**Comment by alphapapa** [comment]
@pkazmier Thanks!  Glad to have this finally merged.  Thanks for your patience.

**Pull request closed without merging**
