### PR TITLE
Add :category selector for filtering out specific categories

### PR DESCRIPTION
**Pull request by balajisivaraman**
First of all, thanks for a wonderful package. For a long time, I wanted to get a cleaner agenda view to let me better focus on things I should really get out of the way in a particular day. This package seems like a Godsend to me. :smiley: 

Secondly, this is my use-case. My Org file has really clean categories that I use for sub-headings, instead of relying on tags. This may not be a good Org practice, but it has really served me well so far. It looks somewhat like this.

```org
* Tasks
   :PROPERTIES:
   :CATEGORY: Tasks
   :END:

* Finances
   :PROPERTIES:
   :CATEGORY: Finance
   :END:

* Work/Company Name
  :PROPERTIES:
  :CATEGORY: Work
  :END:

* Projects
   :PROPERTIES:
   :CATEGORY: Projects
   :END:

* Blogging
   :PROPERTIES:
   :CATEGORY: Blogging
   :END:

* Reading
   :PROPERTIES:
   :CATEGORY: Reading
   :END:

* Watching
   :PROPERTIES:
   :CATEGORY: Watching
   :END:
```

When I began using this package, the first thing I did was look for a `:category` selector to help me organized my Agenda based on my categories and then priorities within them. I was surprised to find that this feature did not exist so far.

So, I have added a `:category` selector as part of this PR. I really hope you see the general usefulness of this feature. :smiley: 

P.S. I really need help with the `results.el` file. When I ran the `cask exec test/run -U` followed by `cask exec test/run --debug`, it screwed up the formatting of the `results.el` file though all the tests did pass in my machine. If you were to give me suggestions, I will work on fixing them properly.

Many thanks in advance!

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi!  Thank you very much for the kind words, and for taking the time to put this together.  I'm glad you find it useful, and it looks like you did a great job. I really appreciate your digging into the tests and adding one for this. 

It seems that most of the test result changes are due to whitespace from tag indentation. There's probably another org variable that needs to be added to the test macro to ensure the default setting is used for the tests, rather than the setting in the developer's config.  However, I see that a few of the scheduled repeaters changed also, and I'm not sure what caused that; maybe it's another variable that we need to add. If you have time, feel free to look for the right variables to add, or I will soon. 

It's a good idea to add the category selector. I hadn't thought of it because I don't use categories much, and there's already the auto-category selector. But one of the great things about Org is how it allows a wide variety of styles, so this is a good addition. 

We might consider adding a new entry at the bottom of the test data file to test this, instead of changing that one, which would also reduce some of the diff.  Maybe you can come up with something amusing in the theme.  ;)

I'll look at this in more detail soon, when I'm at a computer. Thanks!

**Comment by balajisivaraman** [comment]
@alphapapa, Thank you for the quick response. I have added the variable `org-agenda-tags-column` to the test macro and that has neatly formatted everything in the results file. Hopefully that should fix everything.

**Comment by alphapapa** [comment]
Hi again,

That has made the results consistent, but it still results in most of the test results changing.

I actually steered you wrong, I think, because I forgot that I have the code:

```el
(org-super-agenda--test-get-custom-group-members 'org-agenda)
```

Which automatically adds the default values of all customizable variables to the test.

I think the problem is that we're using different Org versions.  What version of Org are you using?  I'm on 9.0.5 at the moment, and the default value of `org-agenda-tags-column` is `'auto`.  The test macro sets `(frame-width)` and `(window-width)` to use consistent values, so that combined with `org-agenda-tags-column` being `'auto` should produce consistent results.

Thanks for your work on this.

**Comment by alphapapa** [comment]
Hello again,

After further investigation, I found that the problem is indeed that I'm on Org 9.0.5, and you're on a newer version of that.  In fact it's my fault, because I submitted a change to Org 9.1 that changed the `org-agenda-tags-column` default, yet I haven't upgraded Org in my personal Emacs config myself!

So I've updated the tests to work correctly on Org 9.1+, and I updated the Cask file to require at leaat Org 9.1.

So if you don't mind a few more steps, please rebase the PR on top of current `master`, and I think that will make the test results differ only by the new feature you've added here.

Thanks for your patience.

**Comment by alphapapa** [comment]
Hi again,

I'm sorry, I forgot all about this.  I'll try to get to it soon, but feel free to post a comment reminding me if I don't.  Thanks.

**Comment by alphapapa** [comment]
@balajisivaraman Thank you very much for your patience.  I made a few small changes, e.g. we can get the category from a text-property in the item string rather than the source buffer, which should be faster.  I also added it to the readme.  Thanks for your contribution!

**Comment by balajisivaraman** [comment]
@alphapapa, No worries. Thank you for merging this. :smiley:

**Pull request closed without merging**
