### PR TITLE
Add option to retain the matched items' original sorting.

### PR DESCRIPTION
**Pull request by Alexander-Miller**
As discussed in #166.

### CODE REVIEW

**Comment by guibor** [comment]
Hi! It looks like the code changed quite a bit since this PR was proposed - but the feature request would be great!

**Comment by Alexander-Miller** [comment]
Yeah, I'll put getting these PRs updated on my agenda.

**Comment by guibor** [comment]
Thanks! Do you still intend to do so? If not I might try to hack something.

**Comment by Alexander-Miller** [comment]
@guibor I tried updating this PR now, but it looks like the package is in a bad state. Something in the setup makes the test run stuck with a non-existent agenda file:

```
❯❯❯ cask exec test/run
Org version: 9.4.6
Test results loaded
Running 71 tests (2021-07-19 20:44:02+0200, selector ‘t’)
org-super-agenda-mode enabled.
Non-existent agenda file ~/org/test.org.  [R]emove from list or [A]bort?
```

Entering either option does not actually do anything all you can do is cancel. The build has been running for half an hour now, so this is not just a local problem. If you have any idea what this is about then please let me know.

**Comment by alphapapa** [comment]
> @guibor I tried updating this PR now, but it looks like the package is in a bad state. Something in the setup makes the test run stuck with a non-existent agenda file:
> 
> ```
> ❯❯❯ cask exec test/run
> Org version: 9.4.6
> Test results loaded
> Running 71 tests (2021-07-19 20:44:02+0200, selector ‘t’)
> org-super-agenda-mode enabled.
> Non-existent agenda file ~/org/test.org.  [R]emove from list or [A]bort?
> ```
> 
> Entering either option does not actually do anything all you can do is cancel. The build has been running for half an hour now, so this is not just a local problem. If you have any idea what this is about then please let me know.

Something has apparently changed in Org since v9.4 was released that is breaking the tests.  

When the last commit to master was made, the tests passed (on 26.3, anyway).  When I run the tests again now, locally, using the sandbox config that I used last (which has Org v9.4 installed), the tests pass.  But when I use a new sandbox config with current versions of dependencies (which gets Org v9.4.6), the tests stall, as you've noticed.  Nothing has changed in this package, so something has been changed in Org.

**Comment by Alexander-Miller** [comment]
@alphapapa What's the path going forward now? I would very much like to get my PRs into a condition where they are fit to be merged, but the kind of changes I am introducing are obviously too much of a risk without a functional test suite.

> By the way, please note that I don't use Cask anymore. Please use the makem.sh script to run the tests

I just went with what I saw in the familiar travis.yml. Unfortunately the sandbox part does not seem to work for me. I ran the setup with `./makem.sh -vv --sandbox="/home/am/.emacs.d/straight/repos/org-super-agenda/SANDBOX" --install-deps --install-linters`, but the packages were still installed into ~/.emacs.d. The sandbox only contained an init.el file. But that's probably a local problem, I don't exactly have what you'd call a standard setup.

**Comment by alphapapa** [comment]
@Alexander-Miller Well, someone will need to dig into the changes that happened in Org between v9.4 and 9.4.6 to find out what is causing an interactive prompt there.  I've seen that prompt before while using Emacs interactively, but I've never known exactly what causes it.  I guess one could start by looking in the Org source for that message, and then maybe look for changes related to code that calls into that code path.  If you'd like to do this, that would be appreciated; if not, I'll probably not do it myself until I'm ready to work on this package again more substantially.

> I just went with what I saw in the familiar travis.yml. Unfortunately the sandbox part does not seem to work for me. I ran the setup with ./makem.sh -vv --sandbox="/home/am/.emacs.d/straight/repos/org-super-agenda/SANDBOX" --install-deps --install-linters, but the packages were still installed into ~/.emacs.d. The sandbox only contained an init.el file. But that's probably a local problem, I don't exactly have what you'd call a standard setup.

I don't know what you mean about your setup, but please update to the latest version of the `makem.sh` script from its own repo.  That will probably fix it, especially if you're using Emacs 28.0.50 (I had to make a change to accommodate early-init).  And generally it's recommended to use a relative path, i.e. `./makem.sh -s.sandbox ...`.

Also, we need to be clear about what Emacs versions are being used here.  It's not generally worth fixing issues that only happen on unreleased versions, and we need to know which released versions are being tested with as well.

**Comment by Alexander-Miller** [comment]
I've got some good news and some bad news. The good news is that I fixed the thing. The bad news is that a bunch of tests are in the red now, and as much as I'd like to get this merged I don't think I've the time budget for such a deep dive.

> I don't know what you mean about your setup, but please update to the latest version of the makem.sh script from its own repo. 

You know the things doom gets up to with its script-driven package management and faster-startup hacks? Basically I have my own version of that.
At any rate updating makem.sh did not help, but it is out of scope anyway - I am using a self-compiled Emacs 28, and trying this on another computer with Emacs 27 did install things correctly.

**Comment by guibor** [comment]
For what it's worth, I started using your branch @Alexander-Miller and it seems to work fine. I now have all items sorted as in my `org-agenda-sorting-stragegy`! So great, and thanks so much.

I think this is super useful so I hope it can be merged once the tests issues are sorted out (I'm not proficient in package management, so not sure I can be of a lot of help...)

**Comment by alphapapa** [comment]
@Alexander-Miller Thank you so much for finding the problem with the tests!  I cherry-picked that commit, pushed it to master, rebased your branch on master, and pushed your branch.

The tests on master all pass locally for me now; we'll see if they do on CI...

**Comment by alphapapa** [comment]
Oh, wait... they pass with my Org 9.4 sandbox, but not with Org 9.4.6.  :(  Well, this is progress, anyway...

**Comment by alphapapa** [comment]
Looks like all the failures are due to whitespaces changes in the agenda prefix format.  Should be simple to update the tests for that, or better, set the prefix format in the tests...

**Comment by alphapapa** [comment]
Nope, wasn't the prefix format.  Something changed internally that removes some whitespace from the agenda lines...

**Comment by alphapapa** [comment]
Wait a second, this looks like it might be a new bug in Org:
```diff
DIFF:
 @@ -2,8 +2,8 @@
 Wednesday   5 July 2017
 
  Today
-  test:        7:02...... Sunrise (12:04 of daylight)
-               8:00...... ----------------
+  test:       7:02......  Sunrise (12:04 of daylight)
+              8:00......  ----------------
               10:00...... ----------------
               12:00...... now - - - - - - - - - - - - - - - - - - - - - - - - -
               12:00...... ----------------
```

See how the old lines aligned the colons in the times, but the new ones have the times one character too far to the left.

**Comment by alphapapa** [comment]
I narrowed down the problem to https://code.orgmode.org/bzg/org-mode/commit/81c7a2dee8e6d0c5e58d0cb4ca97cfc9477ff660:

```
lisp/org-agenda.el: Use "09:00" instead of " 9:00"

* lisp/org-agenda.el (org-get-time-of-day): Use "09:00" instead
of " 9:00" when displaying as a string.

This makes the string more readable, especially for users reading
the agenda with a screen reader.

Reported-by: Sébastien Hinderer
```

```diff
@@ -6995,7 +6995,7 @@ HH:MM."
 	     (h2 (if (and string mod24 (not (and (= m 0) (= h1 24))))
 		     (mod h1 24) h1))
 	     (t0 (+ (* 100 h2) m))
-	     (t1 (concat (if (>= h1 24) "+" " ")
+	     (t1 (concat (if (>= h1 24) "+" "0")
 			 (if (and org-agenda-time-leading-zero
 				  (< t0 1000)) "0" "")
 			 (if (< t0 100) "0" "")
```

**Comment by alphapapa** [comment]
Adding this defun to the test file, which effectively reverts that change while running the test:
```el
(defun org-get-time-of-day (s &optional string mod24)
  "Check string S for a time of day.
If found, return it as a military time number between 0 and 2400.
If not found, return nil.
The optional STRING argument forces conversion into a 5 character wide string
HH:MM."
  (save-match-data
    (when
	(and
	 (or (string-match "\\<\\([012]?[0-9]\\)\\(:\\([0-5][0-9]\\)\\)\\([AaPp][Mm]\\)?\\> *" s)
	     (string-match "\\<\\([012]?[0-9]\\)\\(:\\([0-5][0-9]\\)\\)?\\([AaPp][Mm]\\)\\> *" s))
	 (not (eq (get-text-property 1 'face s) 'org-link)))
      (let* ((h (string-to-number (match-string 1 s)))
	     (m (if (match-end 3) (string-to-number (match-string 3 s)) 0))
	     (ampm (when (match-end 4) (downcase (match-string 4 s))))
	     (am-p (equal ampm "am"))
	     (h1   (cond ((not ampm) h)
			 ((= h 12) (if am-p 0 12))
			 (t (+ h (if am-p 0 12)))))
	     (h2 (if (and string mod24 (not (and (= m 0) (= h1 24))))
		     (mod h1 24) h1))
	     (t0 (+ (* 100 h2) m))
	     (t1 (concat (if (>= h1 24) "+" " ")
			 (if (and org-agenda-time-leading-zero
				  (< t0 1000)) "0" "")
			 (if (< t0 100) "0" "")
			 (if (< t0 10)  "0" "")
			 (number-to-string t0))))
	(if string (concat (substring t1 -4 -2) ":" (substring t1 -2)) t0)))))
```
Leaves us with these test results:
```
Test org-super-agenda-test--:auto-tags backtrace:
  signal(error ("Test failed for body:a5c8edc0db4a93c039964c5762e70420
  error("Test failed for body:%s\nDIFF:\n %s" "a5c8edc0db4a93c039964c5
  (or (equal stored-result new-result) (if (and stored-result new-resu
  (let ((stored-result (gethash body-groups-hash org-super-agenda-test
  (if org-super-agenda-test-show-results nil (let ((stored-result (get
  (let ((body-groups-hash (secure-hash (quote md5) (format "%S" (list 
  (progn (if (> (hash-table-count org-super-agenda-test-results) 0) ni
  (setq value-132 (progn (if (> (hash-table-count org-super-agenda-tes
  (unwind-protect (setq value-132 (progn (if (> (hash-table-count org-
  (if (unwind-protect (setq value-132 (progn (if (> (hash-table-count 
  (let (form-description-133) (if (unwind-protect (setq value-132 (pro
  (let ((value-132 (gensym "ert-form-evaluation-aborted-"))) (let (for
  (closure (t) nil (let ((value-132 (gensym "ert-form-evaluation-abort
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name org-super-agenda-test--:auto-tags :do
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("--title" "makem.sh: org-super-agenda (sandbox: .san
  command-line()
  normal-top-level()
Test org-super-agenda-test--:auto-tags condition:
    (error "Test failed for body:a5c8edc0db4a93c039964c5762e70420
DIFF:
 @@ -10,6 +10,12 @@
  Tags: @town, personal
   test:       Scheduled:  TODO [#C] Get haircut                                                                       :personal:@town:
 
+ Tags: Emacs, computers, elisp, programming, software
+  ideas:      Scheduled:  SOMEDAY Rewrite Emacs in Common Lisp                            :Emacs:elisp:computers:software:programming:
+
+ Tags: Emacs, website
+  test:       Deadline:   CHECK /r/emacs                                                                               :website:Emacs:
+
  Tags: ambition, meetings, universe, world
   ambition:   Sched. 1x:  TODO [#A] Skype with president of Antarctica                             :universe:ambition:world::meetings:
 
@@ -35,15 +41,9 @@
  Tags: bills, spaceship
   test:       In  27 d.:  TODO [#A] Spaceship lease                                                                  :bills:spaceship:
 
- Tags: computers, elisp, emacs, programming, software
-  ideas:      Scheduled:  SOMEDAY Rewrite Emacs in Common Lisp                            :Emacs:elisp:computers:software:programming:
-
  Tags: dinner, food
   test:       18:00...... Scheduled:  TODO Order a pizza                                                                 :food:dinner:
 
- Tags: emacs, website
-  test:       Deadline:   CHECK /r/emacs                                                                               :website:Emacs:
-
  Other items
   test:        7:02...... Sunrise (12:04 of daylight)
                8:00...... ----------------
")
   FAILED   7/71  org-super-agenda-test--:auto-tags

Ran 71 tests, 70 results as expected, 1 unexpected (2021-07-25 17:48:21-0500)

1 unexpected results:
   FAILED  org-super-agenda-test--:auto-tags
```

**Comment by alphapapa** [comment]
@Alexander-Miller Would you mind reporting this issue on the mailing list?  I'm sure that Bastien will recognize the problem and know an easy fix.

**Comment by alphapapa** [comment]
I reported it on the mailing list.  Hopefully a fix will come soon.  I guess the tests will continue to fail on Org 9.4.6, but on other Org versions, they should pass, and hopefully on a yet-to-come 9.4.7.

**Comment by alphapapa** [comment]
Of course, we could add a workaround for just Org 9.4.6, if we have to... but I'd prefer not to...

**Comment by guibor** [comment]
I was hoping to see this merged, in the meantime using Alex' branch worked great for me.
But now, I get the following error:

```
/Users/mdfz/.emacs.d/.cache/quelpa/build/org-super-agenda/org-super-agenda.el -> /var/folders/gx/6fqj2t4x5tn4zml2qp9__9mr00j58f/T/org-super-agendaAveBiX/org-super-agenda-20210922.12322/org-super-agenda.el
/Users/mdfz/.emacs.d/.cache/quelpa/build/org-super-agenda/org-super-agenda.info -> /var/folders/gx/6fqj2t4x5tn4zml2qp9__9mr00j58f/T/org-super-agendaAveBiX/org-super-agenda-20210922.12322/org-super-agenda.info
Wrote /Users/mdfz/.emacs.d/.cache/quelpa/packages/org-super-agenda-readme.txt
Parsing tar file...done
Error getting PACKAGE-DESC: (wrong-type-argument arrayp nil)
(Spacemacs) Error: 
An error occurred while installing org-super-agenda (error: (wrong-type-argument package-desc nil))

```

when using the `retain-sorting` branch. Any idea what I can do about this? Or perhaps there are plans to merge this soon?

Thanks!

**Comment by alphapapa** [comment]
@guibor That error has nothing to do with org-super-agenda.  It indicates an installation problem, maybe related to Spacemacs.

**Comment by alphapapa** [comment]
For future reference, I reported the bug here back in July: https://lists.gnu.org/archive/html/emacs-orgmode/2021-07/msg00603.html  Unfortunately it has still received no response.

**Comment by alphapapa** [comment]
I just posted to the recent "Heading toward Org 9.5" thread, and mailed Bastien privately, asking him to look into it: https://lists.gnu.org/archive/html/emacs-orgmode/2021-09/msg00207.html

**Comment by guibor** [comment]
Thanks for the update! Of course that was related to my setup, and for the record I found the solution [here](https://github.com/syl20bnr/spacemacs/issues/8901).

**Comment by alphapapa** [comment]
Bastien asked me to look into making a patch to fix it, but I wasn't able to re-reproduce it on my system, even using Org 9.4.6.  It's disappointing that this only seems to happen now when run in CI or in batch mode, or something like that.

I don't want that issue to hold up this PR, so I'll see about merging it anyway.

**Comment by alphapapa** [comment]
@Alexander-Miller Thanks for your work and your patience.

**Comment by Alexander-Miller** [comment]
Happy to help.

**Comment by guibor** [comment]
Thank you! This makes a really big difference to my workflow.

**Pull request merged**
