### PR TITLE
Fix typo for osa/separate-by-todo-keywords

### PR DESCRIPTION
**Pull request by seblemaguer**
Just corrected a typo in order to make the readme & the code consistent. I prefered the plural as "priorities" was used

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi, thanks for submitting this.  I actually am conflicted about whether to use plural or singular names for the functions, since so far they accept either one argument or a list.  Either way, it should be consistent.  Which do you think is best?

In the long term, I would like to achieve an API something like the example at the top of the notes.org file, so I consider the current code somewhat experimental.  It will definitely change before being submitted to MELPA (if nothing else, the function names will change to the full package prefix rather than `osa/`.

Please let me know if you have any suggestions about the API.

**Comment by seblemaguer** [comment]
hello,

in this case I think singular is better (but I mean it is not crucial my point of view :D) For the rest of the api, for now I'm really with what it is doing. I am currently using the package and promise if I have suggestions I will come back to you :) . For now I just close the pull request as the bug is solved :)

**Comment by alphapapa** [comment]
Thanks!

**Comment by alphapapa** [comment]
@seblemaguer Hi Sébastien, I just pushed a significant update that adds an "or" filter, which makes it much more powerful.  Please let me know if you have any feedback.  I am thinking about adding an "and" filter, too, but I haven't been able to think of any good example cases.  If you can, please let me know, so I can demonstrate the feature well.  :)  Thanks.

**Comment by alphapapa** [comment]
@seblemaguer I made the OR implicit and greatly reduced the verbosity of the group list.  Please let me know what you think!  :)

**Pull request closed without merging**
